---
- hosts: all
  become: true

  vars:
    golang_package: golang-go

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Go
      apt:
        name: "{{ golang_package }}"
        state: present

    - name: Install prerequisite packages for Docker repo
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    - name: Ensure vagrant uses bash as login shell
      user:
        name: vagrant
        shell: /bin/bash

    - name: Install bash-completion
      apt:
        name: bash-completion
        state: present

    - name: Configure bash completion and prompt in vagrant .bashrc
      blockinfile:
        path: "/home/vagrant/.bashrc"
        create: yes
        marker: "# {mark} provision"
        block: |
          # Enable bash completion
          if [ -f /usr/share/bash-completion/bash_completion ]; then
            . /usr/share/bash-completion/bash_completion
          fi

          # Force prompt
          unset PROMPT_COMMAND
          export PS1='[ \u@\h \w ]\$ '
      become_user: vagrant

    - name: Create keyrings directory if missing
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG Key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker APT repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        mode: '0644'
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: Update apt after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker CE and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
